import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar.jsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Movie List",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-[#1e1c1c]">
      <body className={inter.className}>
        <div className="max-container p-1 ">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
